version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_limited
    ports:
      - "6380:6379"
    mem_limit: 100m # Giới hạn RAM tối đa 100MB
    cpus: 0.5 # Giới hạn CPU: 50%
